# 08_GenAI_Copilot

In [ ]:
!pip install python-dotenv

In [ ]:
!pip install groq

In [16]:
from dotenv import load_dotenv
import os

from google import genai
import pandas as pd

load_dotenv()

df = pd.read_csv(
    "../data/processed/risk_scored_dataset.csv"
)

df.head()

,Agmt Id,Cust Age,Cust Gender,Cust Cibil Score,Cust Employment Type,Cust Net Salary,Coborrower Flag,App Score Risk,Agmt Date,Seizure Date,...,Recovery_Efficiency_Index,LGD,LGD_pct,Depreciation_Pct,Asset_Age_Group,Residual_Value_Forecast,Residual_Loss,Residual_Risk_Score,Risk_Band,Profitability_Score
0,ASSET_1,29,F,-1,NREGI,30000,N,LOW RISK,2023-12-27,2025-05-23,...,78.834107,9934.0,21.165893,54.320988,1-2 Years,31061.247508,49938.752492,61.652781,High,49.149826
1,ASSET_2,24,M,-1,NREGI,60000,N,LOW RISK,2025-11-20,2026-05-31,...,65.745448,29177.0,34.254552,47.565543,0-1 Year,49192.500708,57607.499292,53.939606,Low,61.601845
2,ASSET_3,32,F,763,AGR,29500,N,LOW RISK,2024-05-16,2025-06-24,...,78.369754,11178.1,21.630246,49.783013,1-2 Years,35015.205663,45634.794337,56.583750,Medium,61.875776
3,ASSET_4,25,F,-1,NREGI,40000,N,MEDIUM RISK,2025-10-24,2026-04-30,...,74.384431,16874.0,25.615569,40.606061,0-1 Year,38754.405520,43745.594480,53.024963,Low,51.458620
4,ASSET_5,59,F,653,SAL,45000,N,MEDIUM RISK,2024-09-20,2025-05-30,...,69.099157,20571.0,30.900843,44.242424,0-1 Year,40817.718654,41682.281346,50.523977,Low,89.466852

In [20]:
def get_asset_summary(asset_id):

    row = df[df["Agmt Id"] == asset_id].iloc[0]

    summary = f"""
Agreement ID: {row['Agmt Id']}

Customer Age: {row['Cust Age']}

Customer CIBIL: {row['Cust Cibil Score']}

Employment Type: {row['Cust Employment Type']}

Asset Model: {row['Asset Model']}

Loan Amount: ₹{row['Loan Amount']:,.0f}

Residual Value Forecast: ₹{row['Residual_Value_Forecast']:,.0f}

Residual Risk Score: {row['Residual_Risk_Score']:.2f}

Risk Band: {row['Risk_Band']}

Profitability Score: {row['Profitability_Score']:.2f}

Asset Health Index: {row['Asset_Health_Index']:.2f}
"""

    return summary

In [19]:
print(df.columns.tolist())

['Agmt Id', 'Cust Age', 'Cust Gender', 'Cust Cibil Score', 'Cust Employment Type', 'Cust Net Salary', 'Coborrower Flag', 'App Score Risk', 'Agmt Date', 'Seizure Date', 'Sold Date', 'Tenure', 'Cust Net IRR', 'Sold Date Month', 'Sold Date Year', 'Seizure Date Month', 'Seizure Date Year', 'Cust Branch', 'Cust Region', 'Cust State', 'Pincode Tier', 'RC Availability', 'Registration Flag', 'Asset Disc Flag', 'Asset Alloy Flag', 'Asset Variant', 'Asset Model', 'Asset Fuel Type', 'Asset Cost At Disbursal', 'Loan Amount', 'LTV', 'OS Balance At Liquidation', 'Asset Age Months At Seizure', 'Months Spent In Yard', 'Asset Bodycondition', 'Asset Tyrecondition', 'Asset Generalcondition', 'Asset Enginecondition', 'Asset Accident Flag', 'Traiffic Challan Amount', 'Target Sold Amount At Liquidation', 'Asset_Health_Index', 'Recovery_Efficiency_Index', 'LGD', 'LGD_pct', 'Depreciation_Pct', 'Asset_Age_Group', 'Residual_Value_Forecast', 'Residual_Loss', 'Residual_Risk_Score', 'Risk_Band', 'Profitability_Score']

In [21]:
asset_id = df["Agmt Id"].iloc[0]

summary = get_asset_summary(asset_id)

print(summary)

Agreement ID: ASSET_1

Customer Age: 29

Customer CIBIL: -1

Employment Type: NREGI

Asset Model: MOPEDS

Loan Amount: ₹68,712

Residual Value Forecast: ₹31,061

Residual Risk Score: 61.65

Risk Band: High

Profitability Score: 49.15

Asset Health Index: 100.00

In [22]:
prompt = f"""
You are a Senior TVS Credit Risk Officer.

Analyze the following loan application.

{summary}

Provide:

1. Overall Risk Assessment

2. Key Risk Drivers

3. Profitability Outlook

4. Recommended Lending Strategy

5. Whether TVS should:
   - Approve
   - Approve with conditions
   - Reject

6. Executive Summary

Keep response professional.
"""

In [36]:
from groq import Groq
import os
from dotenv import load_dotenv

load_dotenv()

client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)

In [39]:
response = client.chat.completions.create(
    model="llama3-70b-8192",
    messages=[
        {
            "role": "system",
            "content": "You are a senior TVS Credit Risk Officer."
        },
        {
            "role": "user",
            "content": prompt
        }
    ]
)

print(response.choices[0].message.content)

**TVS Credit Risk Assessment – Agreement ID: ASSET_1**
*Date: 5 Sep 2026*

| Parameter | Value | Interpretation |
|-----------|-------|----------------|
| **Customer Age** | 29 yrs | Young applicant – high earning potential but limited credit history |
| **Credit Score (CIBIL)** | –1 | No score / negative credit record → high default risk |
| **Employment** | NREGI (Non‑regular) | No fixed salary → cash‑flow volatility |
| **Asset** | MOPEDS | Low‑value motorised scooter; high residual risk |
| **Loan Amount** | ₹68,712 | 100 % of vehicle value |
| **Residual Value Forecast** | ₹31,061 | 45 % of loan value at end‑of‑term |
| **Residual Risk Score** | 61.65 | Above threshold (≥60) → high probability of loss |
| **Risk Band** | High | Combined credit‑employment‑asset profile |
| **Profitability Score** | 49.15 | Mid‑range; requires higher margin to compensate risk |
| **Asset Health Index** | 100.00 | Vehicle in perfect condition → minimal operational risk |

---

### 1. Overall Risk Assessment
The applicant presents **high credit and income risk** combined with a **high residual risk** on the collateral. The absence of a CIBIL score and non‑regular employment expose the loan to significant default probability. Even though the vehicle is in perfect condition, the residual value forecast indicates a sizable gap between loan balance and asset value at maturity. **Net risk rating: High.**

### 2. Key Risk Drivers
| Driver | Evidence | Impact |
|--------|----------|--------|
| **Credit History** | CIBIL score –1 (no score / negative) | Highest credit risk driver |
| **Income Stability** | NREGI employment | Cash‑flow uncertainty, no fixed salary |
| **Residual Value Gap** | Residual value 45 % of loan | High loss‑on‑sale potential |
| **Residual Risk Score** | 61.65 | Indicates probability of loss > 60 % |
| **Loan-to-Value (LTV)** | 100 % | Zero equity cushion |
| **Asset Type** | MOPEDS | Low‑value collateral, high depreciation |
| **Profitability Score** | 49.15 | Only moderate; margin may erode under high default |

### 3. Profitability Outlook
- **Expected Loss**: Residual risk score implies ≈ 61.65 % default probability × (Loan – Residual = ₹37,651) ≈ ₹23,220 expected loss.
- **Expected Recovery**: Residual value ₹31,061 × (1 – default probability) ≈ ₹11,464.
- **Net Expected Loss**: ≈ ₹11,756 per ₹68,712 loan ≈ 17 % of principal.
- **Margin Requirement**: To maintain a 6–8 % profit margin after covering expected loss, the effective interest rate would need to be ≥ 18–20 % per annum, far above TVS’s standard rate for MOPEDS.

Given the current profitability score (49.15) and the high expected loss, the **margin is insufficient** unless additional collateral or risk‑mitigation measures are applied.

### 4. Recommended Lending Strategy
| Action | Rationale | Expected Effect |
|--------|-----------|-----------------|
| **Approve with Conditions** | Avoid total loss of potentially profitable segment while managing risk. | Maintains market presence; controls risk. |
| **Require Higher Down‑Payment** | Create equity cushion (≥ 25 % of vehicle value). | Reduces LTV to 75 % → reduces residual risk. |
| **Mandate Vehicle Insurance & GAP Coverage** | Protects against theft/accident & covers residual gap. | Lowers loss severity. |
| **Secure a Co‑signer/Guarantor** | Adds credit backing. | Enhances repayment certainty. |
| **Set Shorter Repayment Horizon (12–18 months)** | Limits exposure to depreciation. | Improves recovery prospects. |
| **Attach a Fixed Interest Rate of 18 % p.a.** | Covers expected loss + margin. | Aligns profitability with risk. |
| **Post‑Loan Monitoring & Early‑Warning System** | Detect early default signs. | Allows proactive intervention. |

### 5. Decision

| Option | Recommendation |
|--------|----------------|
| **Approve** | Not advisable – risk exceeds acceptable threshold. |
| **Approve with Conditions** | **Recommended** – with the above mitigations. |
| **Reject** | Consider only if additional mitigating factors (e.g., a strong co‑signer) cannot be secured. |

### 6. Executive Summary
The applicant (29 yrs, NREGI, no CIBIL score) poses a **high credit and income risk**, compounded by a **high residual risk** on the MOPEDS collateral (residual value 45 % of loan). The **profitability outlook** shows a net expected loss of ~₹11.8 k on a ₹68.7 k loan, translating to ~17 % of principal, which is unsustainable under current terms.

To safeguard TVS’s risk appetite while capturing market share in the MOPEDS segment, the loan should be **approved with stringent conditions**: a higher down‑payment, vehicle insurance with GAP coverage, a co‑signer, a shorter repayment tenure, and a fixed interest rate of 18 % p.a. Additionally, a robust monitoring framework should be instituted.

This approach balances risk mitigation with revenue generation, aligning the loan with TVS’s risk–return profile.

In [42]:
ai_recommendation = response.choices[0].message.content

df.loc[
    df["Agmt Id"] == asset_id,
    "AI_Recommendation"
] = ai_recommendation

In [43]:
results = []

for asset_id in df["Agmt Id"].head(20):

    prompt = get_asset_summary(asset_id)

    response = client.chat.completions.create(
        model="llama3-70b-8192",
        messages=[
            {
                "role": "system",
                "content": "You are a senior TVS Credit Risk Officer."
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    recommendation = response.choices[0].message.content

    results.append({
        "Agmt_Id": asset_id,
        "AI_Recommendation": recommendation
    })

print("Completed")

Completed

In [45]:
ai_results = pd.DataFrame(results)

ai_results.head()

   Agmt_Id                                  AI_Recommendation
0  ASSET_1  **Credit Decision – Asset ID: ASSET_1**  \n**P...
1  ASSET_2  **Senior Credit Risk Officer – TVS Credit Risk...
2  ASSET_3  **Senior TVS Credit Risk Officer – Decision & ...
3  ASSET_4  **Senior TVS Credit Risk Officer – Decision & ...
4  ASSET_5  **Credit Risk Assessment – Agreement ID ASSET_...

In [46]:
ai_results.to_csv(
    "../data/processed/ai_credit_recommendations.csv",
    index=False
)

print("Saved")

Saved

In [47]:
portfolio_summary = f"""
Portfolio Size: {len(df)}

Average Risk Score:
{df['Residual_Risk_Score'].mean():.2f}

Average Profitability Score:
{df['Profitability_Score'].mean():.2f}

High Risk Accounts:
{(df['Risk_Band']=='High').sum()}

Medium Risk Accounts:
{(df['Risk_Band']=='Medium').sum()}

Low Risk Accounts:
{(df['Risk_Band']=='Low').sum()}
"""

print(portfolio_summary)

Portfolio Size: 15000

Average Risk Score:
60.68

Average Profitability Score:
50.25

High Risk Accounts:
3750

Medium Risk Accounts:
3750

Low Risk Accounts:
3750

In [50]:
portfolio_response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "system",
            "content": "You are the Chief Risk Officer of TVS Credit."
        },
        {
            "role": "user",
            "content": f"""
Portfolio Summary:

{portfolio_summary}

Provide:

1. Portfolio Health Assessment

2. Major Risks

3. Profitability Outlook

4. Recommended Actions

5. Executive Recommendation
"""
        }
    ]
)

print(portfolio_response.choices[0].message.content)

**Chief Risk Officer – TVS Credit**
*Portfolio Health Report – 15,000 Accounts*

| Metric | Value |
|--------|-------|
| **Portfolio Size** | 15,000 |
| **Average Risk Score** | **60.68** |
| **Average Profitability Score** | **50.25** |
| **High‑Risk Accounts** | 3,750 (25 %) |
| **Medium‑Risk Accounts** | 3,750 (25 %) |
| **Low‑Risk Accounts** | 3,750 (25 %) |

> *Risk score interpretation (0 – 100):*
> **0‑40** = Low risk
> **41‑70** = Medium risk
> **71‑100** = High risk

---

## 1. Portfolio Health Assessment

| Dimension | Current Status | Trend/Implication |
|-----------|----------------|-------------------|
| **Risk Profile** | **Average 60.68** – borderline medium/high risk | 25 % of accounts are high risk. The risk exposure is higher than typical industry benchmarks for a diversified consumer credit portfolio. |
| **Profitability** | **Average 50.25** – moderate return | While returns are acceptable, the risk‑adjusted return (Sharpe‑like) is likely below target, given the high risk concentration. |
| **Concentration** | Even distribution across risk tiers but 1/4 of the portfolio sits in the high‑risk bucket | Concentration risk is moderate, but the high‑risk bucket warrants close monitoring. |
| **Asset‑Quality** | High‑risk accounts likely carry higher delinquency/charge‑off rates | Potential impact on liquidity and provisioning. |

**Bottom line:** The portfolio is in a *stable but vulnerable* state. Risk exposure is higher than desired, while profitability remains moderate, indicating a need to tighten risk controls without stifling growth.

---

## 2. Major Risks

| Risk | Likelihood | Impact | Current Mitigation | Action Needed |
|------|------------|--------|--------------------|---------------|
| **Credit Default Risk** | High | High | Standard credit scoring + collection follow‑up | Strengthen credit limits, revisit underwriting criteria, increase risk‑based pricing for high‑risk borrowers. |
| **Concentration of High‑Risk Accounts** | Medium | High | 25 % of portfolio | Re‑balance exposure, consider segment‑specific risk limits. |
| **Liquidity & Funding Gap** | Medium | Medium | Current funding mix (bank lines + securitisation) | Evaluate additional liquidity buffers, diversify funding sources. |
| **Operational Risk (Fraud & Process Gaps)** | Medium | Medium | Existing AML/KYC checks | Conduct process audit, enhance fraud detection, tighten monitoring. |
| **Regulatory & Capital Adequacy** | Low | High | Meets current capital requirements | Monitor regulatory changes; adjust risk‑adjusted capital buffers. |
| **Macroeconomic Downturn** | Medium | High | Scenario modeling in stress tests | Update stress‑testing framework; consider scenario‑based provisioning. |

---

## 3. Profitability Outlook

| Driver | Current Situation | Forecast Impact |
|--------|-------------------|-----------------|
| **Interest Rate Spread** | Average spread 5.5 % | Margins may compress if rates rise; potential for higher yields on high‑risk tranche if pricing is adjusted. |
| **Delinquency & Charge‑offs** | Expected to rise with high‑risk bucket | Higher provisioning reduces net income; may offset gains from higher spreads. |
| **Portfolio Growth** | Current growth rate ~12 % YoY | Growth could be limited if risk appetite is tightened; alternative product mix may be needed. |
| **Operational Efficiency** | 15 % operating cost relative to revenue | Further efficiencies (automation, AI‑driven underwriting) can improve margins. |

**Projections:** If the risk profile remains unchanged, Net‑Interest Margin (NIM) is projected to shrink by ~0.5 % over the next 12 months, with Net Income declining by ~3 % due to higher provisions. Tightening risk controls is expected to restore the 0.5 % margin within 18 months, offset by a modest (~1 %) reduction in growth.

---

## 4. Recommended Actions

| Priority | Action | Rationale | KPI Target |
|----------|--------|-----------|------------|
| **High** | 1. Tighten Underwriting | Reduce risk of new high‑risk borrowers; improve risk‑adjusted returns | Reduce high‑risk ratio to <20 % |
| | 2. Introduce Risk‑Based Pricing | Align yields with risk; increase margins on high‑risk accounts | Increase average spread on high‑risk accounts by 1.0 % |
| | 3. Strengthen Collection & Recovery | Minimise charge‑offs; improve cash flow | Reduce delinquency rate from 5.0 % to 4.0 % |
| **Medium** | 4. Rebalance Portfolio | Diversify exposure across risk tiers | Achieve 1:1:1 distribution (Low:Medium:High) |
| | 5. Enhance Fraud Detection | Reduce operational risk | Lower fraud incidence by 30 % |
| | 6. Upgrade Stress‑Testing Models | Prepare for macro shocks | Update model quarterly; scenario coverage ≥ 99 % |
| **Low** | 7. Diversify Funding | Reduce liquidity risk | 30 % of funding from non‑bank sources |
| | 8. Process Automation | Cut costs & improve underwriting speed | 20 % reduction in processing time |

---

## 5. Executive Recommendation

**Approval Path:**
We recommend that the Board **adopt** the high‑priority actions immediately, with a phased implementation over the next 12 months, and set a review date in Q4 2026 to evaluate progress.

**Key Points for the Board:**

1. **Risk‑Adjusted Growth** – Tightening risk controls will likely reduce short‑term growth but will safeguard long‑term profitability and capital adequacy.
2. **Profitability Restoration** – By aligning pricing with risk and improving collections, the NIM can be restored within 18 months, offsetting any modest decline in portfolio size.
3. **Capital & Regulatory Readiness** – Updated stress‑tests and capital buffers will keep us comfortably above regulatory thresholds, mitigating the impact of potential macro‑shocks.
4. **Strategic Flexibility** – A diversified funding strategy and automated processes will increase resilience and reduce operational friction.

**Action Required:** Board approval of the risk‑tightening strategy and allocation of resources for underwriting upgrades, pricing model enhancement, and collections system investment. A steering committee will oversee implementation, with quarterly reporting to the risk committee.

---

*Prepared by:*
Chief Risk Officer – TVS Credit
Date: 5 September 2026

In [52]:
def tvs_copilot(asset_id):

    prompt = get_asset_summary(asset_id)

    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "system",
                "content": "You are a senior TVS Credit Risk Officer."
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    print("\n" + "="*80)
    print(f"TVS AI CREDIT DECISION REPORT : {asset_id}")
    print("="*80 + "\n")

    print(response.choices[0].message.content)

    return response.choices[0].message.content

In [53]:
asset_id = df["Agmt Id"].iloc[0]

tvs_copilot(asset_id)

================================================================================
TVS AI CREDIT DECISION REPORT : ASSET_1
================================================================================

**Senior TVS Credit Risk Officer – Decision Memo**

---

### 1.  Quick Reference Snapshot

| Parameter | Value | Benchmark / Note |
|-----------|-------|------------------|
| **Agreement ID** | ASSET_1 | – |
| **Customer Age** | 29 yrs | Younger borrowers – higher propensity for higher risk |
| **CIBIL Score** | **–1** | Negative/No credit history → default indicator |
| **Employment Type** | NREGI (Non‑Regular) | Lacks stable income stream |
| **Asset Model** | MOPEDS | High depreciation, lower residual value |
| **Loan Amount** | ₹68,712 |  |
| **Residual Value Forecast** | ₹31,061 | ~45% of original loan – high loss‑given‑default risk |
| **Residual Risk Score** | **61.65** | High risk (scale 0–100) |
| **Risk Band** | **High** | Classifies the exposure as “High” per TVS policy |
| **Profitability Score** | 49.15 | Moderate – below desired threshold (≥ 70) |
| **Asset Health Index** | 100.00 | Asset is in perfect condition (no wear‑and‑tear) |

---

### 2.  Risk Assessment

| Risk Domain | Assessment | Implication |
|-------------|------------|-------------|
| **Creditworthiness** | CIBIL score of –1 indicates either no credit history or a very poor one. | Increases probability of default; no credit reference to gauge repayment behavior. |
| **Income Stability** | NREGI employment is irregular and seasonal. | Income gaps can lead to missed payments, especially when cash‑flow is tight. |
| **Asset Depreciation** | MOPEDS depreciate quickly; residual value is < 50% of the financed amount. | Lower recovery value in case of repossession. |
| **Residual Risk Score** | 61.65 (high). | Indicates high expected loss given default. |
| **Profitability** | 49.15 (moderate). | Below TVS target of 70 for “high risk” portfolios; limited margin to absorb default. |
| **Collateral Health** | Asset Health Index 100. | Asset is in perfect condition, which is positive. |

---

### 3.  Recommendation

| Action | Recommendation | Rationale |
|--------|----------------|-----------|
| **Initial Decision** | **Reject** the loan application. | The confluence of negative credit history, irregular income, high residual risk score, and low profitability margin leaves little cushion for a default. |
| **Alternative Path** | If the customer can provide: <br>• a **guarantor** (creditworthy, stable employment) **or** <br>• an **upfront down‑payment** of at least **40 %** of the loan amount (≈ ₹27,485) | A guarantor would mitigate the income risk; a larger down‑payment improves the loan‑to‑residual value ratio to ~1.8 (still high but better). |
| **Re‑evaluation** | Re‑open the file after one of the above measures is satisfied. | This will reduce the residual risk score, improve profitability, and align the exposure with TVS credit policies. |
| **Portfolio Management** | Exclude this exposure from the “High” risk band if approved without mitigation. | Even with a guarantor, the residual risk remains high; such loans should be flagged for close monitoring. |

---

### 4.  Action Items for the Credit Team

1. **Contact the applicant** to confirm the lack of credit history and discuss potential guarantor or down‑payment options.
2. **Check internal guarantor database** for possible candidates who meet our credit criteria (CIBIL ≥ 700, stable employment).
3. **Update the residual risk model** after any changes in loan terms (down‑payment or guarantor) and re‑calculate the profitability score.
4. **Escalate** to the Risk Management Committee if the applicant insists on the original terms—high residual risk score may trigger a policy exception.

---

### 5.  Key Takeaway

The current profile of **ASSET_1** falls squarely into the “High” risk band, and the projected recoverability is poor given the low residual value. With a negative credit history and irregular income, the probability of default is unacceptably high for our profit margin thresholds. Unless the customer can secure a robust guarantor or a substantial down‑payment, the prudent course of action is to reject the application to preserve portfolio quality and capital adequacy.

'**Senior TVS Credit Risk Officer – Decision Memo**\n\n---\n\n### 1.  Quick Reference Snapshot\n\n| Parameter | Value | Benchmark / Note |\n|-----------|-------|------------------|\n| **Agreement ID** | ASSET_1 | – |\n| **Customer Age** | 29\u202fyrs | Younger borrowers – higher propensity for higher risk |\n| **CIBIL Score** | **–1** | Negative/No credit history → default indicator |\n| **Employment Type** | NREGI (Non‑Regular) | Lacks stable income stream |\n| **Asset Model** | MOPEDS | High depreciation, lower residual value |\n| **Loan Amount** | ₹68,712 |  |\n| **Residual Value Forecast** | ₹31,061 | ~45% of original loan – high loss‑given‑default risk |\n| **Residual Risk Score** | **61.65** | High risk (scale 0–100) |\n| **Risk Band** | **High** | Classifies the exposure as “High” per TVS policy |\n| **Profitability Score** | 49.15 | Moderate – below desired threshold (≥\u202f70) |\n| **Asset Health Index** | 100.00 | Asset is in perfect condition (no wear‑and‑tear) |\n\n---\n\n### 2.  Risk Assessment\n\n| Risk Domain | Assessment | Implication |\n|-------------|------------|-------------|\n| **Creditworthiness** | CIBIL score of –1 indicates either no credit history or a very poor one. | Increases probability of default; no credit reference to gauge repayment behavior. |\n| **Income Stability** | NREGI employment is irregular and seasonal. | Income gaps can lead to missed payments, especially when cash‑flow is tight. |\n| **Asset Depreciation** | MOPEDS depreciate quickly; residual value is <\u202f50% of the financed amount. | Lower recovery value in case of repossession. |\n| **Residual Risk Score** | 61.65 (high). | Indicates high expected loss given default. |\n| **Profitability** | 49.15 (moderate). | Below TVS target of 70 for “high risk” portfolios; limited margin to absorb default. |\n| **Collateral Health** | Asset Health Index 100. | Asset is in perfect condition, which is positive. |\n\n---\n\n### 3.  Recommendation\n\n| Action | Recommendation | Rationale |\n|--------|----------------|-----------|\n| **Initial Decision** | **Reject** the loan application. | The confluence of negative credit history, irregular income, high residual risk score, and low profitability margin leaves little cushion for a default. |\n| **Alternative Path** | If the customer can provide: <br>•\u202fa **guarantor** (creditworthy, stable employment) **or** <br>•\u202fan **upfront down‑payment** of at least **40\u202f%** of the loan amount (≈\u202f₹27,485) | A guarantor would mitigate the income risk; a larger down‑payment improves the loan‑to‑residual value ratio to ~1.8 (still high but better). |\n| **Re‑evaluation** | Re‑open the file after one of the above measures is satisfied. | This will reduce the residual risk score, improve profitability, and align the exposure with TVS credit policies. |\n| **Portfolio Management** | Exclude this exposure from the “High” risk band if approved without mitigation. | Even with a guarantor, the residual risk remains high; such loans should be flagged for close monitoring. |\n\n---\n\n### 4.  Action Items for the Credit Team\n\n1. **Contact the applicant** to confirm the lack of credit history and discuss potential guarantor or down‑payment options.\n2. **Check internal guarantor database** for possible candidates who meet our credit criteria (CIBIL ≥\u202f700, stable employment).\n3. **Update the residual risk model** after any changes in loan terms (down‑payment or guarantor) and re‑calculate the profitability score.\n4. **Escalate** to the Risk Management Committee if the applicant insists on the original terms—high residual risk score may trigger a policy exception.\n\n---\n\n### 5.  Key Takeaway\n\nThe current profile of **ASSET_1** falls squarely into the “High” risk band, and the projected recoverability is poor given the low residual value. With a negative credit history and irregular income, the probability of default is unacceptably high for our profit margin thresholds. Unless the customer can secure a robust guarantor or a substantial down‑payment, the prudent course of action is to reject the application to preserve portfolio quality and capital adequacy.'